name: Boston dataset
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          touch ./report_test.md
          apt-get install python3
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 MLops.py >> ./report_test.md
          

          # echo "## Model metrics" > ./report_test.md
          # cat evalution.txt >> ./report_test.md
          # cat metrics.txt >> ./report_test.md
          # echo "## Data viz" >> ./report_test.md
          # cml-publish feature.png --md >> ./report_test.md
          # cml-publish target.png --md >> ./report_test.md
          
          # cml-send-comment ./report_test.md