name: Boston dataset
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: cml_run
      env:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sudo apt-get install python3
        sudo python3 -m pip install --upgrade pip
        sudo pip install -r requirements.txt
        python3 MLops.py
        touch ./report.md
        echo "## Model metrics" > ./report.md
        cat evalution.txt >> ./report.md
        cat metrics.txt >> ./report.md
        echo "## Data viz" >> ./report.md
        cml-publish feature.png --md >> ./report.md
        cml-publish target.png --md >> ./report.md
        cml-send-comment ./report.md
