name: Boston dataset
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          apt-get install python3
          pip3 install -r requirements.txt
          python MLops.py
          
          echo "## Model metrics" > report.md
          cat evalution.txt >> report.md
          cat metrics.txt >> report.md
          echo "## Data viz" >> report.md
          cml-publish feature.png.png --md >> report.md
          cml-publish target.png.png --md >> report.md
          
          cml-send-comment report.md
